### PR TITLE
feat: display labels on execution detail page

### PR DESCRIPTION
**Pull request by blaketastic2**
# TL;DR
This PR adds the spec labels to the execution details page

## Type
 - [ ] Bug Fix
 - [X] Feature
 - [ ] Plugin

## Are all requirements met?

 - [X] Code completed
 - [X] Smoke tested
 - [X] Unit tests added
 - [ ] Code documentation added
 - [ ] Any pending items have an associated Issue

image

### CODE REVIEW

**Comment by JamesHoover** [comment]
This is great, thank you. A few items I would like to see:

1. Updated color, yellow is too prominent, update to a secondary color like grey.

2. Overflow states:
- what happens when a single label is very long?
- what happens when you have 3+ rows of labels?

3. Empty state, what happens when there are no labels?

4. Interactions, are these intended to be clickable or copyable?

**Comment by blaketastic2** [comment]
Here's what it looks like with more(both longer and more rows)

**Comment by blaketastic2** [comment]
Here's an updated version with the `info` color set on the Chip.

**Comment by blaketastic2** [comment]
Empty state, the column doesn't show. Would you prefer the `---` behaviour instead?

Also, there is no functionality on the Chips. If someone wants to add something later(like copy to clipboard), I think it should be trivial. Do you think this is ok?

**Comment by JamesHoover** [comment]
> Empty state, the column doesn't show. Would you prefer the `---` behaviour instead?
> 
> Also, there is no functionality on the Chips. If someone wants to add something later(like copy to clipboard), I think it should be trivial. Do you think this is ok?

Yes, I would prefer the `---` behavior for the empty state for consistency and discovery. Otherwise this looks good to me. Thank you for your contribution!

**Comment by blaketastic2** [comment]
Ok, done.

image

**Review by jsonporter — APPROVED** [review]

**Pull request merged**
